"""empty message

Revision ID: 600611775459
Revises: b5eee7056cfd
Create Date: 2021-07-26 11:23:45.635284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '600611775459'
down_revision = 'b5eee7056cfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('origin_country', sa.String(length=255), nullable=True),
    sa.Column('image_id', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('public_id')
    )
    op.create_table('image',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('public_id')
    )
    op.create_table('album',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.Column('artist_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.public_id'], ),
    sa.PrimaryKeyConstraint('public_id')
    )
    op.create_table('rating',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.Column('number_of_stars', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('artist_id', sa.String(length=255), nullable=True),
    sa.Column('album_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['album.public_id'], ),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.public_id'], ),
    sa.PrimaryKeyConstraint('public_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    op.drop_table('album')
    op.drop_table('image')
    op.drop_table('artist')
    # ### end Alembic commands ###
