"""empty message

Revision ID: 6212c46f4b93
Revises: ebd59ad63162
Create Date: 2021-07-27 16:13:08.154519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6212c46f4b93'
down_revision = 'ebd59ad63162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('release_year', sa.Integer(), nullable=True))
    op.add_column('album', sa.Column('genre', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'album', 'genre', ['genre'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'album', type_='foreignkey')
    op.drop_column('album', 'genre')
    op.drop_column('album', 'release_year')
    # ### end Alembic commands ###
