"""empty message

Revision ID: 85c8a7ffd224
Revises: 78907caaafa8
Create Date: 2021-07-29 14:25:30.557815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c8a7ffd224'
down_revision = '78907caaafa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'likes')
    op.drop_column('rating', 'likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comment', sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
