"""empty message

Revision ID: c321770e01d5
Revises: 600611775459
Create Date: 2021-07-26 12:42:44.980451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c321770e01d5'
down_revision = '600611775459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('user_id', sa.String(length=255), nullable=False))
    op.add_column('rating', sa.Column('likes', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rating', 'user', ['user_id'], ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rating', type_='foreignkey')
    op.drop_column('rating', 'likes')
    op.drop_column('rating', 'user_id')
    # ### end Alembic commands ###
