"""empty message

Revision ID: 0f98bae2228f
Revises: 146bd1f024f0
Create Date: 2021-08-16 08:34:33.587414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f98bae2228f'
down_revision = '146bd1f024f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('filename', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'image', ['filename'])
    op.drop_column('image', 'path')
    op.alter_column('rating', 'number_of_likes',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rating', 'number_of_likes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('image', sa.Column('path', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'image', type_='unique')
    op.drop_column('image', 'filename')
    # ### end Alembic commands ###
