"""empty message

Revision ID: 3ced8965201a
Revises: f61e7ca45e8e
Create Date: 2021-08-24 07:33:41.074229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ced8965201a'
down_revision = 'f61e7ca45e8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('number_of_likes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rating', 'number_of_likes')
    # ### end Alembic commands ###
