"""empty message

Revision ID: 6dee7ba85f0b
Revises: 
Create Date: 2021-08-23 14:31:57.459065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dee7ba85f0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('total_note', sa.Float(), nullable=False))
    op.add_column('artist', sa.Column('total_note', sa.Float(), nullable=False))
    op.add_column('genre', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('genre', 'image')
    op.drop_column('artist', 'total_note')
    op.drop_column('album', 'total_note')
    # ### end Alembic commands ###
