"""empty message

Revision ID: 78907caaafa8
Revises: 
Create Date: 2021-07-28 13:06:28.623595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78907caaafa8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'album', 'image', ['image_id'], ['id'])
    op.create_foreign_key(None, 'artist', 'image', ['image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artist', type_='foreignkey')
    op.drop_constraint(None, 'album', type_='foreignkey')
    # ### end Alembic commands ###
