"""empty message

Revision ID: a387a4543b62
Revises: 4ab9782d1773
Create Date: 2021-08-17 17:01:27.014442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a387a4543b62'
down_revision = '4ab9782d1773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rating', 'number_of_likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('number_of_likes', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
