"""empty message

Revision ID: a9637ce90856
Revises: a1735b1c89da
Create Date: 2021-08-16 08:25:38.295263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9637ce90856'
down_revision = 'a1735b1c89da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('number_of_likes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rating', 'number_of_likes')
    # ### end Alembic commands ###
