"""empty message

Revision ID: f808fb63870c
Revises: f83b62740b50
Create Date: 2021-11-08 11:09:58.961512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f808fb63870c'
down_revision = 'f83b62740b50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
